/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esprit.tunRecrut.ui;

import com.esprit.tunRecrut.dao.AnnonceDAO;
import com.esprit.tunRecrut.dao.ContratDAO;
import com.esprit.tunRecrut.dao.ExprienceDAO;
import com.esprit.tunRecrut.dao.MetierDAO;
import com.esprit.tunRecrut.dao.NiveauDAO;
import com.esprit.tunRecrut.dao.RegionDAO;
import com.esprit.tunRecrut.dao.TypeDAO;
import com.esprit.tunRecrut.entities.Contrat;
import com.esprit.tunRecrut.entities.Experience;
import com.esprit.tunRecrut.entities.Metier;
import com.esprit.tunRecrut.entities.Niveau;
import com.esprit.tunRecrut.entities.Region;
import com.esprit.tunRecrut.entities.TypeEmploi;
import com.esprit.tunRecrut.ui.OffreModel;
import com.esprit.tunRecrut.ui.administrateur.ListeOffreTable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Haithem
 */
public class OffreUI extends javax.swing.JFrame {

    /**
     * Creates new form OffreUI
     */
    public OffreUI() {
        initComponents();
        initRegion();
        initContrat();
        initExprience();
        initType();
        initNiveau();
        initMetier();
    }

    public void setFilter(String keyword, int contrat_id, int experience_id, int type_id, int niveau_id, int region_id) {
        jTable1.setModel(new OffreModel(keyword, contrat_id, experience_id, type_id, niveau_id, region_id, 2));
        jScrollPane1.setViewportView(jTable1);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        keyword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        contrat = new javax.swing.JComboBox();
        niveau = new javax.swing.JComboBox();
        exprience = new javax.swing.JComboBox();
        region_id = new javax.swing.JComboBox();
        type = new javax.swing.JComboBox();
        jButtonFilter = new javax.swing.JButton();
        jButtonDeleteFilter = new javax.swing.JButton();
        jButtonAfficherOffre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jTable1.setModel(new com.esprit.tunRecrut.ui.OffreModel("",0,0,0,0,0,2));
        jTable1.setRowHeight(28);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mots clées");

        contrat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Selectionnez type de contrat ---" }));

        niveau.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Selectionnez un niveau d'étude ---" }));

        exprience.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---- Selectionnez une exprience ---" }));

        region_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Selectionnez un région ---" }));

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Selctionnez un type d'emploi ---" }));

        jButtonFilter.setText("Filtrer");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonDeleteFilter.setText("Effacer");

        jButtonAfficherOffre.setText("Afficher");
        jButtonAfficherOffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficherOffreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exprience, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contrat, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(niveau, javax.swing.GroupLayout.Alignment.TRAILING, 0, 262, Short.MAX_VALUE)
                            .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(region_id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(keyword)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonFilter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteFilter)
                                .addGap(366, 366, 366))
                            .addComponent(jButtonAfficherOffre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keyword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonFilter)
                    .addComponent(jButtonDeleteFilter))
                .addGap(18, 18, 18)
                .addComponent(region_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exprience, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAfficherOffre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonAfficherOffre.setEnabled(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        Object candidat_id = jTable1.getValueAt(row, 0);
        System.out.println("id = " + candidat_id.hashCode());
        jButtonAfficherOffre.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        setFilter(keyword.getText(), contrat.getSelectedIndex(), exprience.getSelectedIndex(), type.getSelectedIndex(), niveau.getSelectedIndex(), region_id.getSelectedIndex());
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButtonAfficherOffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficherOffreActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Object offre_id = jTable1.getValueAt(row, 0);
        new OffreShowUI(offre_id.hashCode());
    }//GEN-LAST:event_jButtonAfficherOffreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OffreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OffreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OffreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OffreUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(OffreUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(OffreUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(OffreUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(OffreUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                new OffreUI().setVisible(true);
            }
        });
    }
    
    private void initContrat() {
        ContratDAO contratdao = new ContratDAO();
        List<Contrat> contrats = contratdao.getAllContart();
        for (Contrat contrat_ : contrats) {
            contrat.addItem(contrat_.getNom());
        }
    }

    private void initExprience() {
        ExprienceDAO expriencedao = new ExprienceDAO();
        List<Experience> expriences = expriencedao.getAllExprience();
        for (Experience exprience_ : expriences) {
            exprience.addItem(exprience_.getNom());
        }
    }

    private void initType() {
        TypeDAO typedao = new TypeDAO();
        List<TypeEmploi> types = typedao.getAllType();
        for (TypeEmploi type_ : types) {
            type.addItem(type_.getNom());
        }
    }

    private void initNiveau() {
        NiveauDAO niveaudao = new NiveauDAO();
        List<Niveau> niveaux = niveaudao.getAllNiveau();
        for (Niveau niveau_ : niveaux) {
            niveau.addItem(niveau_.getNom());
        }
    }

    public void initRegion() {
        RegionDAO regiondao = new RegionDAO();
        List<Region> regions = regiondao.getAllRegion();
        for (Region region : regions) {
            region_id.addItem(region.getName());
        }

    }

    public void initMetier() {
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        MetierDAO regiondao = new MetierDAO();
        List<Metier> regions = regiondao.getAllMetier();
        for (Metier region : regions) {
            listModel.addElement(region.getNom());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox contrat;
    private javax.swing.JComboBox exprience;
    private javax.swing.JButton jButtonAfficherOffre;
    private javax.swing.JButton jButtonDeleteFilter;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField keyword;
    private javax.swing.JComboBox niveau;
    private javax.swing.JComboBox region_id;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
